### ISSUE TITLE
Is it poosible to remove the raindrop in real time ? 

### ISSUE THREAD

**Issue by aalzooke** [jinnovation/derain-net#3]
I'm wondering  if its possible to remove the raindrop in real time instead of single image? 
Also please share the dataset i can't download it from the link you provide 
Thank you

**Comment by jinnovation** [comment]
I'm assuming you're referring to video processing.

This is and will not be supported, as I am limiting the scope of this project strictly to the problem space of the authors' publication.

**Comment by aalzooke** [comment]
Thank you, when i download the dataset, i can't open the images, can you please look into this. 
I need to test and train my model. 
Thank you

**Comment by jinnovation** [comment]
If you're referring to an issue with https://github.com/jinnovation/rainy-image-dataset, please open an issue on that project with more details.
