### ISSUE TITLE
wrong output

### ISSUE THREAD

**Issue by Hrhythm** [jinnovation/derain-net#5]
in your file derain.py  your output is the img_base,it is not the result of the derained image.

**Comment by zhaojianghe16** [comment]
@Hrhythm Hi, it seems that you can run the code. I was wondering if this code is complete in terms of having training and testing. I didn't see there's testing code after we trained the code. Do we need to write on our own to test if the training is done properly?

**Comment by jinnovation** [comment]
Apologies for the confusion. This project is a work-in-progress, so there are bound to be some bugs and missing functionality, as you both have mentioned.

For now, I'd encourage you two to take what's currently there for what it is, and follow the project for new developments as they come up. Thanks for the interest 👍
