### ISSUE TITLE
Where is the test code after we trained the neural network

### ISSUE THREAD

**Issue by zhaojianghe16** [jinnovation/derain-net#6]
Hi,
     It seems there is no test code to see if the training is done properly.
     Could please show us how you test it in the end?

Best,
Zhaojiang

**Comment by jinnovation** [comment]
> It seems there is no test code to see if the training is done properly.

That is correct. This project is very much a work-in-progress, so I simply have not gotten around to setting that up yet.

I'll be sure to update this project when I have it set up.

**Comment by zhaojianghe16** [comment]
Thank you for your response. I am a student at UCLA doing summer research right now. I look up the original code, and It seems that you try to make the code better than the original one in terms of neatness and readability. My professor is very interested in this topic. May I ask what is your plan? Are you planning to get them run faster or ...?

**Comment by jinnovation** [comment]
> It seems that you try to make the code better than the original one in terms of neatness and readability

Yes and no. My goal here is to get more concrete experience in not only modeling/training, but also the TensorFlow framework itself.

> My professor is very interested in this topic. 

That's great to hear. Who are you working with?

> May I ask what is your plan? Are you planning to get them run faster or ...?

My broad goals are to complete all aspects of this project, including—but not limited to—the following:
* Completing the training flow
* Implementing and completing the testing flow
* "Production-izing" the work by giving users a single executable `derain` executable that they can download for their own immediate use.

It is not my goal to improve upon the original authors' results, nor do I have any plans to go down that path.

I will also say that this project is very much an exploratory pet project of mine. As such, I'm not subjecting myself to any strict deadlines per se.

Hope that helps.
