### ISSUE TITLE
what is the structure of dataset

### ISSUE THREAD

**Issue by yasohasakii** [jinnovation/derain-net#9]
hi i want to use derainnet to do some deblur work,and my data isnot *jpg or *png image so i cannt open with tf.image ,i want to build dataset but i dont know what kind of structure the dataset in your code is. so please tell me if you would.

**Comment by jinnovation** [comment]
Hi @caibojun, you can find more details about the dataset I'm using here at [jinnovation/rainy-image-dataset](https://github.com/jinnovation/rainy-image-dataset); I've made some recent additions to the README there that might be of use to you.

Feel free to open an issue there if you'd like to know more about the dataset specifically.
